version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "RustLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nr3d5wv8xmke"
s3_prefix = "RustLambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RootUrl=\"{{resolve:ssm:/account/root-url:1}}\" SslCert=\"{{resolve:ssm:/account/ssl-cert:1}}\""
