AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Rust
Parameters:
  RootUrl:
    Type: String
    Default: '{{resolve:ssm:/account/root-url:1}}'
  SslCert:
    Type: String
    Default: '{{resolve:ssm:/account/ssl-cert:1}}'
Resources:
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: s3://cold-lambda/RustLambda/3ce02faf2b5e8d6a71bd55d1df124fb7
      StageName: Prod
      Variables:
        ServiceApiFunction:
          Ref: ServiceApiFunction
  ServiceApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: HelloRust
      CodeUri: s3://cold-lambda/RustLambda/1fd7a2a12bd6a535c5a7cebd10a562e7
      Runtime: provided
      Handler: bootstrap.my_handler
      MemorySize: 1024
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:*
          Resource: '*'
      Environment:
        Variables:
          RootUrl:
            Ref: RootUrl
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServiceApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServiceApi
            Path: /{proxy+}
            Method: ANY
Outputs:
  DeploymentStrategy:
    Description: Deployment strategy instruction for the service
    Value: ez_zdt
  ApiUrl:
    Description: The API URL
    Value:
      Fn::Sub: https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaServiceApiLogs:
    Description: Api Lambda Logs
    Value:
      Fn::Sub: https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=/aws/lambda/${ServiceApiFunction};streamFilter=typeLogStreamPrefix
